apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deploy
  labels:
    app: hotstar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
        - name: hotstar-cont
          image: sai798187/hotstarimg:latest
          ports:
            - containerPort: 8080
